App\Form\Model\WineDto:
    properties:
      name:
        - NotBlank: ~
        - Length:
            min: 3
            max: 255
            minMessage: 'The name must be at least {{ limit }} characters long'
            maxMessage: 'The name cannot be longer than {{ limit }} characters'
      year:
        - NotBlank: ~
        - Type: integer
        - Range:
            min: 1900
            max: 2024
            minMessage: 'The year must be at least {{ limit }}'
            maxMessage: 'The year cannot be greater than {{ limit }}'
            
